name: Protector
version: '1.0-SNAPSHOT'
main: io.pproton96.protector.Protector
api-version: '1.21'
authors: [PProton96]
description: Simple authentication plugin
commands:
  getpassword:
    description: Console only command to get password.
    usage: /getpassword
  alliumtroll:
    description: Fills target player's inventory with allium.
    usage: /alliumtroll <player-name>